service: serverless-linkshortener
frameworkVersion: '3'
useDotenv: true

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-lift

custom:
  esbuild:
    minify: true
    watch:
      pattern: ['./index.ts', 'src/**/*.ts']
      ignore: ['.serverless/**/*', '.build']

  USERS_TABLE_NAME: usersTable
  LINKS_TABLE_NAME: linksTable
  LINK_ID_LENGTH: 6
  SENDER_EMAIL_ADDRESS: maxymkoval2510@gmail.com
  JWT_ACCESS_SECRET: ${env:JWT_ACCESS_SECRET}
  JWT_REFRESH_SECRET: ${env:JWT_REFRESH_SECRET}

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-central-1

  httpApi:
    cors: true
    authorizers:
      jwt-auth:
        type: request
        functionName: authorizer

  environment:
    QUEUE_URL: ${construct:jobs.queueUrl}
    USERS_TABLE: ${self:custom.USERS_TABLE_NAME}
    LINKS_TABLE: ${self:custom.LINKS_TABLE_NAME}
    JWT_ACCESS_SECRET: ${self:custom.JWT_ACCESS_SECRET}
    JWT_REFRESH_SECRET: ${self:custom.JWT_REFRESH_SECRET}
    LINK_ID_LENGTH: ${self:custom.LINK_ID_LENGTH}
    SENDER_EMAIL_ADDRESS: ${self:custom.SENDER_EMAIL_ADDRESS}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - ses:SendEmail
          Resource:
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.USERS_TABLE_NAME}*"
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.LINKS_TABLE_NAME}*"
            - "arn:aws:ses:${aws:region}:${aws:accountId}:identity/${self:custom.senderEmailAddress}*"
            - "arn:aws:ses:${aws:region}:${aws:accountId}:configuration-set/my-first-configuration-set"

constructs:
  jobs:
    type: queue
    worker:
      handler: apps/notify/worker.sendEmail

functions:
  - ${file(./auth-functions.yml)}
  - ${file(./links-functions.yml)}

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.USERS_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    linksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.LINKS_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH


